### PR TITLE
speed up the map loading time, add restaurant icon

### PR DESCRIPTION
**Pull request by marodev**

### CODE REVIEW

**Comment by SegiNyn** [comment]
Awesome we now have a marker :)
Tho I don't know why but the map doesn't load...it only shows the tile.

**Comment by marodev** [comment]
@SegiNyn Good point. It doesn't seem to work on an emulator. Do you have a chance to test it on a real phone?

**Comment by SegiNyn** [comment]
Oh no I don't have the usb cable to connect the Mac to my phone.. I can test it tomorrow

**Comment by marodev** [comment]
I rolled back to the default tile source. It is not so fast as the other one but works fine on emulators.

**Comment by SegiNyn** [comment]
Okay yes now it works :) Perfect!!!

**Pull request merged**
